### ISSUE TITLE
No module named 'src.data'

### ISSUE THREAD

**Issue by bbb801** [VinBDI-MedicalImagingTeam/midl2020-cnnlstm-ich#2]
Dear Sir，

When I used 'main.py' and implement 'from src.data import RSNAHemorrhageDS3d, Qure500DS', there is an error 'ModuleNotFoundError: No module named 'src.data'. It seems I cannot find 'data' file in your 'src' file. Any advice?

**Comment by dattran2346** [comment]
Hi @bbb801, the `data` directory was accidentally ignore by my local `.gitignore`, I have committed the code.
Regards.
